/* eslint-disable */
// Generated by scripts/generate-site-versions.mjs — do not edit manually.

export type SiteVersionEntry = {
  version: string;
  hash: string;
  fullHash: string;
  date: string;
  message: string;
};

export type SiteVersions = {
  current: SiteVersionEntry | null;
  history: SiteVersionEntry[];
};

export const siteVersions: SiteVersions = {
  "current": {
    "version": "0.1.50",
    "hash": "f7ecdbf",
    "fullHash": "f7ecdbf2f9c9be3a851023f0ccc76070a750cfe4",
    "date": "2026-06-07T17:21:30+03:00",
    "message": "Refresh release notes and stabilize Gmail signer E2E selectors."
  },
  "history": [
    {
      "version": "0.1.50",
      "hash": "f7ecdbf",
      "fullHash": "f7ecdbf2f9c9be3a851023f0ccc76070a750cfe4",
      "date": "2026-06-07T17:21:30+03:00",
      "message": "Refresh release notes and stabilize Gmail signer E2E selectors."
    },
    {
      "version": "0.1.49",
      "hash": "ebfa019",
      "fullHash": "ebfa019f10e1ef4ed066357ff1211003ba3165cd",
      "date": "2026-06-07T17:20:23+03:00",
      "message": "Fix CI Docker startup when git history is unavailable."
    },
    {
      "version": "0.1.48",
      "hash": "74a88cf",
      "fullHash": "74a88cfa83743dc2cb03b3c8f622947fcce507cd",
      "date": "2026-06-07T17:13:15+03:00",
      "message": "Add footer release notes synced from git commits."
    },
    {
      "version": "0.1.47",
      "hash": "a125d18",
      "fullHash": "a125d1858c4f2c1db0b6c0226f0a54346b3c740c",
      "date": "2026-06-07T17:05:20+03:00",
      "message": "Fix E2E reliability and refresh Hebrew product demo."
    },
    {
      "version": "0.1.46",
      "hash": "c69f23c",
      "fullHash": "c69f23cc69b3686de2b9d8b6f35ec47b46dc6354",
      "date": "2026-06-07T15:53:36+03:00",
      "message": "Add skippable onboarding tour with embedded demo video."
    },
    {
      "version": "0.1.45",
      "hash": "529d87e",
      "fullHash": "529d87e54179c92fbb19e34813f8baa2eb8b35c1",
      "date": "2026-06-07T13:51:17+03:00",
      "message": "Add GitHub Actions E2E workflow with Docker Compose."
    },
    {
      "version": "0.1.44",
      "hash": "d933ec2",
      "fullHash": "d933ec21bf83e5e0fcf02c3d9ac8b915b40d3e5b",
      "date": "2026-06-07T13:45:26+03:00",
      "message": "Improve PDF loading, document wizard, and AI provider support."
    },
    {
      "version": "0.1.43",
      "hash": "45169fd",
      "fullHash": "45169fd312eaabf90fc7ab59d883dc02fd328a65",
      "date": "2026-06-06T19:29:58+03:00",
      "message": "Add Motion-orchestrated entries for Settings and Dashboard."
    },
    {
      "version": "0.1.42",
      "hash": "b2110ee",
      "fullHash": "b2110ee99c5d7a8004afc88fe8a39c41098a7dd2",
      "date": "2026-06-06T19:26:13+03:00",
      "message": "Add 200ms color transitions for smooth theme switching."
    },
    {
      "version": "0.1.41",
      "hash": "340f7d2",
      "fullHash": "340f7d28ad0680f5ede827d26cf81744741185de",
      "date": "2026-06-06T18:10:49+03:00",
      "message": "Add Playwright e2e: theme persistence across reload and tabs."
    },
    {
      "version": "0.1.40",
      "hash": "7de416e",
      "fullHash": "7de416e9e2db365230a8a30afc92dc42a29dbde9",
      "date": "2026-06-06T18:09:05+03:00",
      "message": "Replace window.confirm with Dialog, inline errors with Sonner toasts."
    },
    {
      "version": "0.1.39",
      "hash": "59a78f0",
      "fullHash": "59a78f0c19d8ccb3dac69cb337a97880d0c470cd",
      "date": "2026-06-06T18:05:07+03:00",
      "message": "Refactor DashboardClient: ui/Tabs, ui/Checkbox, ui/Button, token card layout."
    },
    {
      "version": "0.1.38",
      "hash": "ca26f90",
      "fullHash": "ca26f909179b7c8b54780aaef23c7ac205e27ceb",
      "date": "2026-06-06T18:02:09+03:00",
      "message": "Refactor Navbar: token-styled links, custom user dropdown, Settings entry."
    },
    {
      "version": "0.1.37",
      "hash": "c4c1003",
      "fullHash": "c4c1003faec265452e1184b539278a70ac03fbd5",
      "date": "2026-06-06T17:58:25+03:00",
      "message": "Refactor StatusBadge to wrap ui/Badge with status→variant mapping."
    },
    {
      "version": "0.1.36",
      "hash": "ae76cb0",
      "fullHash": "ae76cb0eacfc2e9c4a4f72785360ea4e75619a08",
      "date": "2026-06-06T17:56:41+03:00",
      "message": "Add /settings page with Appearance section and ThemePicker."
    },
    {
      "version": "0.1.35",
      "hash": "c436086",
      "fullHash": "c436086394cc307f30dd2cf6af62f4b6a267e818",
      "date": "2026-06-06T17:54:59+03:00",
      "message": "Wire Clerk persistence: server theme resolver + onPersist callback."
    },
    {
      "version": "0.1.34",
      "hash": "d9c65b2",
      "fullHash": "d9c65b266dc12ad2a5b5d4559aad8483ef31b999",
      "date": "2026-06-06T17:52:16+03:00",
      "message": "Add Server Action to persist theme to Clerk publicMetadata."
    },
    {
      "version": "0.1.33",
      "hash": "4962508",
      "fullHash": "4962508d225f0afa8a1ccf4a193deccdeabb4a7b",
      "date": "2026-06-06T17:50:49+03:00",
      "message": "Add server-side theme resolver (cookie → Clerk → default)."
    },
    {
      "version": "0.1.32",
      "hash": "8844ee0",
      "fullHash": "8844ee0970dec73315a0a504faf7f02a2b8e01ae",
      "date": "2026-06-06T17:49:23+03:00",
      "message": "Mirror locale pattern: theme cookie + early-return bootstrap."
    },
    {
      "version": "0.1.31",
      "hash": "acb9b40",
      "fullHash": "acb9b40809356cb2ce8939bd7b06b46d669b0af3",
      "date": "2026-06-06T17:47:59+03:00",
      "message": "Use real U+2019 apostrophe in Settings description, restore single-quote delimiter."
    },
    {
      "version": "0.1.30",
      "hash": "6ccb72d",
      "fullHash": "6ccb72dce854b63376962b7531992cbd6b0822f2",
      "date": "2026-06-06T17:46:35+03:00",
      "message": "Use curly Unicode apostrophe in Settings appearance description."
    },
    {
      "version": "0.1.29",
      "hash": "44d9430",
      "fullHash": "44d94309819fba332c2ed705fa550732ab93fef6",
      "date": "2026-06-06T17:44:04+03:00",
      "message": "Add i18n strings for Settings page and Appearance section."
    },
    {
      "version": "0.1.28",
      "hash": "74e819d",
      "fullHash": "74e819d05ba9c9e0e4b8ffa2406e9627d036ab6f",
      "date": "2026-06-06T17:18:22+03:00",
      "message": "Add Phase 2 implementation plan for UI design system."
    },
    {
      "version": "0.1.27",
      "hash": "b0e859e",
      "fullHash": "b0e859e7052036edb19e5b941f54235db87d0825",
      "date": "2026-06-06T16:20:26+03:00",
      "message": "Target wrapper via data-testid in RTL test."
    },
    {
      "version": "0.1.26",
      "hash": "e1040b4",
      "fullHash": "e1040b43b337592d8bd1d5de1ecba65d5a90bfba",
      "date": "2026-06-06T16:17:56+03:00",
      "message": "Revert redundant useEffect in PreviewClient dir sync."
    },
    {
      "version": "0.1.25",
      "hash": "2afcfb3",
      "fullHash": "2afcfb33da75814cb373a9b7ad0cde7e7a6ad352",
      "date": "2026-06-06T16:16:16+03:00",
      "message": "Strengthen RTL toggle test with direct dir attribute check."
    },
    {
      "version": "0.1.24",
      "hash": "e5682e5",
      "fullHash": "e5682e54e9420fb68c3ff85cbd7b23b82be0f5a9",
      "date": "2026-06-06T15:44:24+03:00",
      "message": "Add Playwright smoke test for /dev/tokens preview route."
    },
    {
      "version": "0.1.23",
      "hash": "1873395",
      "fullHash": "1873395584d9ee2a17766aced32db919389df4a9",
      "date": "2026-06-06T15:42:04+03:00",
      "message": "Gate /dev/tokens behind NODE_ENV so prod returns 404"
    },
    {
      "version": "0.1.22",
      "hash": "982561b",
      "fullHash": "982561b388e65950b04708c9af8a1c12f43af291",
      "date": "2026-06-06T15:39:47+03:00",
      "message": "Add /dev/tokens preview route showing all primitives in all themes."
    },
    {
      "version": "0.1.21",
      "hash": "2356f4e",
      "fullHash": "2356f4e69b70b356443d27bab79e764e6206b689",
      "date": "2026-06-06T15:37:04+03:00",
      "message": "Document ThemePicker a11y deferral and inline-swatch rationale."
    },
    {
      "version": "0.1.20",
      "hash": "2e716a9",
      "fullHash": "2e716a95be884ae158300d1c31abb5dda3d699d1",
      "date": "2026-06-06T15:32:13+03:00",
      "message": "Add ThemePicker radio-card group for Humane, Classic, Modern."
    },
    {
      "version": "0.1.19",
      "hash": "ffc031e",
      "fullHash": "ffc031edc86374a367bb6f80f443cb6b6aae4186",
      "date": "2026-06-06T15:30:23+03:00",
      "message": "Drop next-themes from sonner Toaster (project is light-only in v1)."
    },
    {
      "version": "0.1.18",
      "hash": "08c9123",
      "fullHash": "08c912398e157781d2ff75726e5796d7eec80ee1",
      "date": "2026-06-06T15:19:31+03:00",
      "message": "Install 14 shadcn primitives and mount Sonner Toaster in root layout."
    },
    {
      "version": "0.1.17",
      "hash": "58dc890",
      "fullHash": "58dc890e73ca1d10dbccb99979e29f72fc85b529",
      "date": "2026-06-06T14:51:10+03:00",
      "message": "Wire ThemeProvider and theme bootstrap script into root layout."
    },
    {
      "version": "0.1.16",
      "hash": "2e37254",
      "fullHash": "2e37254afde95193b148d5e29186c443ea1598ae",
      "date": "2026-06-06T14:48:53+03:00",
      "message": "Add ThemeProvider with useSyncExternalStore + cross-tab sync."
    },
    {
      "version": "0.1.15",
      "hash": "66a348d",
      "fullHash": "66a348de3d78dc13a9ec7db262547c8300739f60",
      "date": "2026-06-06T14:46:37+03:00",
      "message": "Add theme module: constants, parser, persister, bootstrap script."
    },
    {
      "version": "0.1.14",
      "hash": "f1705f6",
      "fullHash": "f1705f6cbf5d3582932431bce9a6a98c6b43dad6",
      "date": "2026-06-06T14:44:32+03:00",
      "message": "Wire Tailwind utilities to design tokens via CSS variables."
    },
    {
      "version": "0.1.13",
      "hash": "9ba2b88",
      "fullHash": "9ba2b88ada046f78d1cc6d34d529fbc967d9a930",
      "date": "2026-06-06T14:41:03+03:00",
      "message": "Define design tokens for Humane, Classic, and Modern themes."
    },
    {
      "version": "0.1.12",
      "hash": "421dcbb",
      "fullHash": "421dcbb17343729a3906243db983e016ab1a8548",
      "date": "2026-06-06T14:39:01+03:00",
      "message": "Add shadcn components.json and cn() utility helper."
    },
    {
      "version": "0.1.11",
      "hash": "8a57531",
      "fullHash": "8a5753184072ecf41edb046ad73b52954a6f9f3e",
      "date": "2026-06-06T14:36:33+03:00",
      "message": "Add shadcn/ui runtime dependencies for design system."
    }
  ]
} as const;
