/* eslint-disable */
// Generated by scripts/generate-site-versions.mjs — do not edit manually.

export type SiteVersionEntry = {
  version: string;
  hash: string;
  fullHash: string;
  date: string;
  message: string;
};

export type SiteVersions = {
  current: SiteVersionEntry | null;
  history: SiteVersionEntry[];
};

export const siteVersions: SiteVersions = {
  "current": {
    "version": "0.1.184",
    "hash": "fef16e6",
    "fullHash": "fef16e62a7c92c08b1639f40af733cff60063e61",
    "date": "2026-08-24T22:31:05+03:00",
    "message": "Tag signer-facing fields so the sign button can find them"
  },
  "history": [
    {
      "version": "0.1.184",
      "hash": "fef16e6",
      "fullHash": "fef16e62a7c92c08b1639f40af733cff60063e61",
      "date": "2026-08-24T22:31:05+03:00",
      "message": "Tag signer-facing fields so the sign button can find them"
    },
    {
      "version": "0.1.183",
      "hash": "63884ee",
      "fullHash": "63884ee4184d2aa67fda105b487c5036f8ec8e3a",
      "date": "2026-08-24T19:05:35+03:00",
      "message": "fix button"
    },
    {
      "version": "0.1.182",
      "hash": "fdffe5e",
      "fullHash": "fdffe5e94bd3374f97fb494acbf5f5d61ee90cee",
      "date": "2026-08-24T18:37:53+03:00",
      "message": "Let guests load the PDF worker"
    },
    {
      "version": "0.1.181",
      "hash": "521b8e8",
      "fullHash": "521b8e8ac1831ca4d80a3e4080908ac8f7b4bcd0",
      "date": "2026-08-24T17:47:02+03:00",
      "message": "Merge pull request #15 from yaronkinar/feature/skip-contract-upload-for-templates"
    },
    {
      "version": "0.1.180",
      "hash": "d4a5aae",
      "fullHash": "d4a5aae1e7af58fe5a4a30aa02e1697aa0cb3be0",
      "date": "2026-08-24T17:45:38+03:00",
      "message": "Let template flows past the contract upload"
    },
    {
      "version": "0.1.179",
      "hash": "c325d4f",
      "fullHash": "c325d4f0c41b9c0484ecf58134476bf22ea03e71",
      "date": "2026-07-29T16:43:31+03:00",
      "message": "Never fill the form from an attached contract either"
    },
    {
      "version": "0.1.178",
      "hash": "82f9573",
      "fullHash": "82f9573ff9b0bad6d418ea57a670c54d52fcbed2",
      "date": "2026-07-29T16:23:09+03:00",
      "message": "Stop AI-detected values from landing in the form"
    },
    {
      "version": "0.1.177",
      "hash": "520127a",
      "fullHash": "520127a227dbe221a8f8205833d9d30000980dfd",
      "date": "2026-07-29T15:31:06+03:00",
      "message": "Re-mint the template PDF URL when its signed link expires"
    },
    {
      "version": "0.1.176",
      "hash": "4618de3",
      "fullHash": "4618de3ca8a2005b19c9cfcb64e2a3a120037e98",
      "date": "2026-07-29T15:14:05+03:00",
      "message": "Translate the reference-value copy hint"
    },
    {
      "version": "0.1.175",
      "hash": "838166c",
      "fullHash": "838166c2b4fc1d7629d377eb48cb04d42eb9adcc",
      "date": "2026-07-29T14:56:33+03:00",
      "message": "Add a no-watch dev mode for the API"
    },
    {
      "version": "0.1.174",
      "hash": "821683e",
      "fullHash": "821683e4fac878bc3620fb0cdd05ee950ee6c099",
      "date": "2026-07-29T12:44:52+03:00",
      "message": "Retry the port bind rather than probing it first"
    },
    {
      "version": "0.1.173",
      "hash": "2265157",
      "fullHash": "2265157eb948aeb475e809a3c2a8963e74602a51",
      "date": "2026-07-29T11:33:51+03:00",
      "message": "Wait for the port instead of dying when a restart races itself"
    },
    {
      "version": "0.1.172",
      "hash": "248594c",
      "fullHash": "248594c6001f3efb1b52d153b85881d09a88ed7b",
      "date": "2026-07-29T09:03:51+03:00",
      "message": "Keep signature spots and data fields in their own lanes"
    },
    {
      "version": "0.1.171",
      "hash": "a7a2c2a",
      "fullHash": "a7a2c2a0c5cce8cce943952bfcc6898ae22ac340",
      "date": "2026-07-29T07:11:05+03:00",
      "message": "Extract all pages, and verify reference values against the PDF text"
    },
    {
      "version": "0.1.170",
      "hash": "0d407f6",
      "fullHash": "0d407f6960dfc8d4c492cb79d6b77dbff61a0d2d",
      "date": "2026-07-29T06:58:18+03:00",
      "message": "Stop steering form-field extraction toward signature fields"
    },
    {
      "version": "0.1.169",
      "hash": "a90423f",
      "fullHash": "a90423f3c03ca36093161e09b0f01fe381900020",
      "date": "2026-07-29T06:37:09+03:00",
      "message": "Don't restart the sign flow when the signature pad is already open"
    },
    {
      "version": "0.1.168",
      "hash": "4874707",
      "fullHash": "48747076d77e45e62119c41738974bda27b9d1f2",
      "date": "2026-07-29T06:33:02+03:00",
      "message": "Auto-scroll the page list while dragging a field"
    },
    {
      "version": "0.1.167",
      "hash": "b1a306d",
      "fullHash": "b1a306d1f9f47eae830ce321d9f92de397972ab5",
      "date": "2026-07-28T20:48:35+03:00",
      "message": "Retry the sign step when the watch-mode dev API restarts"
    },
    {
      "version": "0.1.166",
      "hash": "eb8eab5",
      "fullHash": "eb8eab5746008ef62c5f1eaf93c11ce808149202",
      "date": "2026-07-28T20:44:54+03:00",
      "message": "Allow dragging form fields across pages too"
    },
    {
      "version": "0.1.165",
      "hash": "533dbf9",
      "fullHash": "533dbf949fad84eb9be4daf6da537644dcc21da5",
      "date": "2026-07-28T18:47:06+03:00",
      "message": "Merge branch 'worktree-template-field-reference-values'"
    },
    {
      "version": "0.1.164",
      "hash": "d2fa3bb",
      "fullHash": "d2fa3bb4e41a1b28c722dd7eafcadc9da165c712",
      "date": "2026-07-28T18:43:09+03:00",
      "message": "Translate templates pages to i18n keys"
    },
    {
      "version": "0.1.163",
      "hash": "021288a",
      "fullHash": "021288ac90f6dbbbace972704debc85c2f8b8155",
      "date": "2026-07-28T18:35:58+03:00",
      "message": "Allow dragging template signature fields across pages"
    },
    {
      "version": "0.1.162",
      "hash": "f57fcc0",
      "fullHash": "f57fcc0d48f4c0ab67a3021a9af9d616d942bc18",
      "date": "2026-07-28T14:56:47+03:00",
      "message": "Preview extracted reference values in the template editor field list"
    },
    {
      "version": "0.1.161",
      "hash": "7e3d354",
      "fullHash": "7e3d3545a4ad3a8d811bdb78f7f73fc7edcdbc34",
      "date": "2026-07-28T14:54:38+03:00",
      "message": "Fix truncation, label nesting, contrast, and clipboard errors in reference hint"
    },
    {
      "version": "0.1.160",
      "hash": "ef3a99b",
      "fullHash": "ef3a99b614dc1d7a8fa8b79fabe36d11b6dcd5ad",
      "date": "2026-07-28T14:46:54+03:00",
      "message": "Show copyable reference values in the document fill panel"
    },
    {
      "version": "0.1.159",
      "hash": "38e23c7",
      "fullHash": "38e23c7a9b32a9b7780c9a84098a7f4ce34413f3",
      "date": "2026-07-28T14:40:46+03:00",
      "message": "Preserve referenceValue when re-detecting document form fields"
    },
    {
      "version": "0.1.158",
      "hash": "4e387d6",
      "fullHash": "4e387d6b04bde2a752f14ef90d2ea4b80ea77b9f",
      "date": "2026-07-28T14:31:08+03:00",
      "message": "Propagate referenceValue from templates onto created documents"
    },
    {
      "version": "0.1.157",
      "hash": "ed7c405",
      "fullHash": "ed7c40504009afccb380925bb1682bc75f5e7e7e",
      "date": "2026-07-28T14:22:19+03:00",
      "message": "Persist and propagate referenceValue through template APIs"
    },
    {
      "version": "0.1.156",
      "hash": "5bade46",
      "fullHash": "5bade46c335a458bcd3ca81be377df2f9d07f5d0",
      "date": "2026-07-28T14:14:57+03:00",
      "message": "Extract per-cell table fields with exact reference values from filled PDFs"
    },
    {
      "version": "0.1.155",
      "hash": "246d160",
      "fullHash": "246d160a770817fe13ebc7dd9f32d5a2e5749a9c",
      "date": "2026-07-28T14:11:31+03:00",
      "message": "Document RTL ordering limitation in resolveFieldReferenceValues"
    },
    {
      "version": "0.1.154",
      "hash": "88ccbb9",
      "fullHash": "88ccbb99dabaa55e550cda2c2c9a01d7a1d17f60",
      "date": "2026-07-28T14:06:35+03:00",
      "message": "Add resolveFieldReferenceValues for exact PDF text-layer field values"
    },
    {
      "version": "0.1.153",
      "hash": "fd97650",
      "fullHash": "fd976502895e8ba3ef27416e6e6a91d5108df191",
      "date": "2026-07-28T14:02:23+03:00",
      "message": "Add referenceValue to PdfFormFieldTemplate and extraction mapping"
    },
    {
      "version": "0.1.152",
      "hash": "c3a23e9",
      "fullHash": "c3a23e92e9c96e3c3ed984fe898cdf81348c991e",
      "date": "2026-07-28T13:49:42+03:00",
      "message": "Add implementation plan for template field reference values"
    },
    {
      "version": "0.1.151",
      "hash": "310bdd2",
      "fullHash": "310bdd224f8b2b8cfabb72c30d96e9a21f06e2dc",
      "date": "2026-07-28T13:40:20+03:00",
      "message": "Add design spec for template field reference values (copy-from-PDF)"
    },
    {
      "version": "0.1.150",
      "hash": "d59505d",
      "fullHash": "d59505d1745c8d1ef03718b7fd8c2ae8cc6c40d2",
      "date": "2026-07-10T16:37:11+03:00",
      "message": "Add self-hosted Mongo backup service for Railway"
    },
    {
      "version": "0.1.149",
      "hash": "cf6546f",
      "fullHash": "cf6546f7f7c8aed15abd8bda13e7d60f58054ef7",
      "date": "2026-07-09T06:40:41+03:00",
      "message": "Fix flaky e2e downloads on Windows and pin LocalStorageBackend URL behavior"
    },
    {
      "version": "0.1.148",
      "hash": "2ad22ad",
      "fullHash": "2ad22ad51c3190038b65a0da2d63ae4559c4c98b",
      "date": "2026-07-08T14:23:20+03:00",
      "message": "Remove Supabase storage backend in favor of local filesystem"
    },
    {
      "version": "0.1.147",
      "hash": "5272194",
      "fullHash": "5272194b89cc95e366dbd7b24e9ec88c3df59ca9",
      "date": "2026-06-23T08:28:49+03:00",
      "message": "Skip saved signatures with missing storage objects instead of 500ing"
    },
    {
      "version": "0.1.146",
      "hash": "f9d7e55",
      "fullHash": "f9d7e55e771501da80ab8952be6ee63e045f8515",
      "date": "2026-06-22T07:41:46+03:00",
      "message": "Add implementation plan for contract attachment before form fill"
    },
    {
      "version": "0.1.145",
      "hash": "e4803cb",
      "fullHash": "e4803cb2d430f653cfd0e0ab67a0bcade1e4fad0",
      "date": "2026-06-22T07:34:02+03:00",
      "message": "Clean up orphaned source-contract storage objects"
    }
  ]
} as const;
