/** Demo values for the Haknasot form "fill automatically" button. */
export const HAKNASOT_SAMPLE_FORM_VALUES: Record<string, string> = {
  date: '2026-05-21',
  contract_type: 'הרחבה',
  income_ref: 'הכנסות משכירות חניון עירוני',
  manager_ref: '',
  muni_ref: '',
  rent_ref: '',
  building_ref: '',
  service_ref: '',
  contract_number: '2024/087',
  budget_code: 'מכרז 12/2023',
  prev_agency: 'אגף הכנסות',
  submitting_agency: 'אגף רכש',
  supplier_name: 'חברת שירותים עירוניים בע"מ',
  supplier_id: '512345678',
  work_nature: 'מתן שירותי ניקיון ואחזקה למבני ציבור',
  contract_purpose_from: '2024-01-01',
  contract_purpose_until: '2024-12-31',
  budget_prev_1: '2025-06-30',
  budget_prev_2: '',
  budget_prev_3: '',
  current_budget_from: '2026-01-01',
  current_budget_until: '2026-12-31',
  annual_sources: '45,000',
  annual_approval: '12,500',
  expense_budget: '3.14.001',
  income_budget: '',
  annual_commitment: '690,000',
  budget_balance: '50,000 עד 31/12/2026',
  approval_conditions: 'הרחבת היקף השירות לשני מבנים נוספים',
  obligations: 'קיימים ביטוחי אחריות מקצועית וצד ג\'',
};
