#!/usr/bin/env node
/**
 * Writes a minimal .env for Docker Compose in CI (and local CI dry-runs).
 * Never commit the generated .env file.
 */
import fs from 'node:fs';
import path from 'node:path';

const bypassToken = process.env.BYPASS_TOKEN ?? 'ci-bypass-token';
const bypassEmail = process.env.BYPASS_AUTH_EMAIL ?? 'test@example.com';

const contents = `# Generated by scripts/create-ci-env.mjs — do not commit
CLERK_SECRET_KEY=sk_test_playwrightMocksDoNotUseOutsideTests
CLERK_WEBHOOK_SECRET=whsec_ci_test_only
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c3Rlcmxpbmctc3RhcmZpc2gtNzkuY2xlcmsuYWNjb3VudHMuZGV2JA

MONGODB_URI=mongodb://mongodb:27017/docflow
REDIS_URL=redis://redis:6379

STORAGE_DRIVER=local
API_PUBLIC_URL=http://localhost:3001

NEXT_PUBLIC_API_URL=http://localhost:3001
NEXT_PUBLIC_APP_URL=http://localhost:3000
WEB_URL=http://localhost:3000

INVITE_TOKEN_SECRET=ci-invite-secret-for-tests-only

BYPASS_AUTH=true
BYPASS_TOKEN=${bypassToken}
BYPASS_AUTH_EMAIL=${bypassEmail}
NEXT_PUBLIC_BYPASS_AUTH=true
NEXT_PUBLIC_BYPASS_TOKEN=${bypassToken}
`;

const target = path.join(process.cwd(), '.env');
fs.writeFileSync(target, contents, 'utf8');
console.log(`Wrote ${target}`);
